config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :photos

  resources :users, except: [:new, :destroy] do
    resources :photos do
      resources :comments, except: [:show, :update]
    end
  end

  root 'home#index'

  get '/search', to: 'users#search'

  get '/users/:id/friends', to: 'users#friends', as: :friends

  get '/users/:id/requests', to: 'users#requests', as: :requests

  post '/users/:id/befriend', to: 'users#befriend', as: :befriend

  post '/users/:id/accept', to: 'users#accept', as: :accept

  post '/users/:id/deny', to: 'users#deny', as: :deny

  post '/users/:user_id/photos/:id/like', to: 'photos#like', as: :like

  delete '/users/:user_id/photos/:id/dislike', to: 'photos#dislike', as: :dislike

  post '/users/:user_id/photos/:id/tag', to: 'photos#tag', as: :user_photo_taggings

  delete '/users/:user_id/photos/:id/untag/:tagged_user_id', to: 'photos#untag', as: :untag

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo

  scope :newest_first, -> { order('updated_at DESC') }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_photo
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # POST /comments
  # POST /comments.json
  def create
    @comment = @photo.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to request.referer, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      set_photo
      @comment = @photo.comments.find(params[:id])
    end

    def set_photo
      set_user
      @photo = @user.photos.find(params[:photo_id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :photo_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.slim
= simple_form_for [@user, @photo, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.input :content, required: true, autofocus: true, label: false, placeholder: "What's on your mind?", input_html: { class: "form-control", rows: 3 }
  .form-actions
    = f.button :submit, "Add comment", class: "btn btn-primary"

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path