config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :photos

  resources :users, except: [:new, :destroy] do
    resources :photos do
      resources :comments, except: [:show, :update]
    end
  end

  root 'home#index'

  get '/search', to: 'users#search'

  get '/users/:id/friends', to: 'users#friends', as: :friends

  get '/users/:id/requests', to: 'users#requests', as: :requests

  post '/users/:id/befriend', to: 'users#befriend', as: :befriend

  post '/users/:id/accept', to: 'users#accept', as: :accept

  post '/users/:id/deny', to: 'users#deny', as: :deny

  post '/users/:user_id/photos/:id/like', to: 'photos#like', as: :like

  delete '/users/:user_id/photos/:id/dislike', to: 'photos#dislike', as: :dislike

  post '/users/:user_id/photos/:id/tag', to: 'photos#tag', as: :user_photo_taggings

  delete '/users/:user_id/photos/:id/untag/:tagged_user_id', to: 'photos#untag', as: :untag

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :photos
  has_many :friendships
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  scope :accepted, -> () { where("friendships.accepted = 1 OR friendships.accepted = 't'") }

  scope :not_accepted, -> () { where("friendships.accepted IS NULL OR friendships.accepted = 0 OR friendships.accepted = 'f'") }

  def friend_requests
    inverse_friends.not_accepted
  end

  def already_requested?(other_user)
    friends.not_accepted.include? other_user
  end

  def has_requested_friendship?(other_user)
    inverse_friends.not_accepted.include? other_user
  end

  def is_friend?(other_user)
    all_friends.include? other_user
  end

  def all_friends
    friends.accepted + inverse_friends.accepted
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :befriend, :requests, :accept, :deny, :friends]
  before_action :check_permission, only: [:edit, :update, :requests, :friends]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if @user.is_friend?(current_user) || @user == current_user
      @photos = @user.photos.newest_first
    else
      @photos = @user.photos.where(public: true).newest_first
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    @users = User.where("first_name LIKE ? OR last_name LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    render :index
  end

  def friends
    @users = current_user.all_friends
    render :index
  end

  def befriend
    @friendship = Friendship.create(user_id: current_user.id, friend_id: @user.id)
    flash[:notice] = 'Friend request sent'
    redirect_to request.referer
  end

  def accept
    friendship = Friendship.where(user_id: @user.id).first
    friendship.accepted = true
    friendship.save
    redirect_to request.referer
  end

  def deny
    friendship = Friendship.where(user_id: @user.id).first
    friendship.accepted = false
    friendship.save
    redirect_to request.referer
  end

  def requests
    @users = current_user.friend_requests
  end

  private

    def check_permission
      set_user
      redirect_to root_path unless current_user == @user
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message
  .form-group
    = f.input :first_name, required: true, autofocus: true, input_html: { class: "form-control" }
  .form-group
    = f.input :last_name, required: true, input_html: { class: "form-control" }
  .form-actions
    = f.button :submit, "Save", class: "btn btn-primary"

app/views/users/edit.html.slim
.row
  .col-md-4.col-md-offset-4
    h2 Editing user

    == render 'form'

    = link_to 'Show', @user
    '|
    = link_to 'Back', users_path

app/views/users/index.html.slim
.row
  .col-md-4.col-md-offset-4
    h1 Listing users
    .table-responsive
      table.table.users-table
        tbody
          - @users.each do |user|
            - unless current_user and current_user == user
              tr
                td
                  = link_to user.name, user
                - if current_user
                  - if current_user.is_friend?(user)
                    td Friend
                  - elsif current_user.already_requested?(user)
                    td Requested
                  - elsif current_user.has_requested_friendship?(user)
                    td = link_to 'Accept', accept_path(user), method: :post, class: "btn btn-success"
                    td = link_to 'Deny', deny_path(user), method: :post, class: "btn btn-danger"
                  - else
                    td = link_to 'Befriend', befriend_path(user), method: :post, class: "btn btn-primary"

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/requests.html.slim
.row
  .col-md-4.col-md-offset-4
    h1 Friend requests
    .table-responsive
      table.table.users-table
        tbody
          - @users.each do |user|
            - unless current_user and current_user == user
              tr
                td
                  = link_to user.name, user
                td
                  = link_to 'Accept', accept_path(user), method: :post, class: "btn btn-success"
                td
                  = link_to 'Deny', deny_path(user), method: :post, class: "btn btn-danger"

app/views/users/show.html.slim
- if @user && @user == current_user
  h1 My Photos
- else
  h1 #{@user.name}
  hr
  - if current_user
    - if current_user.is_friend?(@user)
      td Friend
    - elsif current_user.already_requested?(@user)
      td Requested
    - elsif current_user.has_requested_friendship?(@user)
      td = link_to 'Accept', accept_path(@user), method: :post, class: "btn btn-success"
      td = link_to 'Deny', deny_path(@user), method: :post, class: "btn btn-danger"
    - else
      td = link_to 'Befriend', befriend_path(@user), method: :post, class: "btn btn-primary"
  h2 #{@user.name}'s photos

- @photos.each do |photo|
  .col-sm-4.index-photo
    = link_to [photo.user, photo] do
      = image_tag photo.file.url
    h4.text-center.photo-description = photo.description
    h5.text-center.photo-time
      - unless photo.public
        span.glyphicon.glyphicon-lock
        | &nbsp;
      = time_ago_in_words photo.updated_at
      | &nbsp;ago