config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :photos

  resources :users, except: [:new, :destroy] do
    resources :photos do
      resources :comments, except: [:show, :update]
    end
  end

  root 'home#index'

  get '/search', to: 'users#search'

  get '/users/:id/friends', to: 'users#friends', as: :friends

  get '/users/:id/requests', to: 'users#requests', as: :requests

  post '/users/:id/befriend', to: 'users#befriend', as: :befriend

  post '/users/:id/accept', to: 'users#accept', as: :accept

  post '/users/:id/deny', to: 'users#deny', as: :deny

  post '/users/:user_id/photos/:id/like', to: 'photos#like', as: :like

  delete '/users/:user_id/photos/:id/dislike', to: 'photos#dislike', as: :dislike

  post '/users/:user_id/photos/:id/tag', to: 'photos#tag', as: :user_photo_taggings

  delete '/users/:user_id/photos/:id/untag/:tagged_user_id', to: 'photos#untag', as: :untag

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  has_many :likes
  has_many :like_users, through: :likes, source: :user

  has_many :taggings
  has_many :tagged_users, through: :taggings, source: :user

  has_attached_file :file
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

  scope :newest_first, -> { order('updated_at DESC') }

  def can_view?(other_user)
    user == other_user || user.is_friend?(other_user) || public
  end

  def has_liked?(other_user)
    like_users.include? other_user
  end

  def taggable_users
    User.all - tagged_users
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_user
  before_action :set_photo, only: [:show, :edit, :update, :like, :dislike, :tag, :untag]
  before_action :check_permission, only: [:new, :create, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @photos = @user.photos
  end

  # GET /users/1
  # GET /users/1.json
  def show
    can_view
    @comments = @photo.comments.where('id is not null').newest_first
    @comment = @photo.comments.new
  end

  def new
    @photo = @user.photos.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @photo = @user.photos.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to [@user, @photo], notice: 'Photo was successfully uploaded.' }
        format.json { render :show, status: :created, location: [@user, @photo] }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to [@user, @photo], notice: 'Photo was successfully uploaded.' }
        format.json { render :show, status: :ok, location: [@user, @photo] }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def like
    like = @photo.likes.create(user_id: current_user.id)
    redirect_to request.referer
  end

  def dislike
    like = @photo.likes.find_by(user_id: current_user.id)
    like.destroy
    redirect_to request.referer
  end

  def tag
    tag = @photo.taggings.create(user_id: params[:tagging][:user_id])
    redirect_to request.referer
  end

  def untag
    tag = @photo.taggings.find_by(user_id: params[:tagged_user_id])
    tag.destroy
    redirect_to request.referer
  end

  private

    def can_view
      set_user
      set_photo
      redirect_to root_path unless @photo.can_view?(current_user)
    end

    def check_permission
      set_user
      redirect_to root_path unless current_user == @user
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_photo
      set_user
      @photo = @user.photos.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:description, :file, :public)
    end
end

app/views/photos/_form.html.slim
= simple_form_for [@user, @photo] do |f|
  - if @photo.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @photo.errors.full_messages.each do |message|
          li = message
  .form-group
    = f.input :description, required: true, autofocus: true, input_html: { class: "form-control" }
  - if params[:action] == 'new'
    .form-group
      = f.input :file
  - else
    .index-photo = image_tag @photo.file.url
  .form-group
    = f.label :public
    = f.input :public, label: false
  .form-actions
    = f.button :submit, "Save", class: "btn btn-primary"

app/views/photos/edit.html.slim
.row
  .col-md-6.col-md-offset-3
    h2 Editing photo

    == render 'form'

app/views/photos/index.html.slim
h1 Listing photos

- @photos.each do |photo|
  .row
    .col-md-4.col-md-offset-4
      = link_to [photo.user, photo] do
        = image_tag photo.file.url
        p = photo.description

app/views/photos/new.html.slim
.row
  .col-md-4.col-md-offset-4
    h2 New photo

    == render 'form'

app/views/photos/show.html.slim
.row
  .col-sm-6
    .index-photo
      = image_tag @photo.file.url
      - if @photo.user == current_user
        = link_to edit_user_photo_path(@photo.user, @photo), class: "btn btn-info left-top" do
            span.glyphicon.glyphicon-edit
    h4.text-center.photo-description
      = "#{@photo.description} by "
      = link_to @photo.user.name, @photo.user
    h5.text-center.photo-time
      - unless @photo.public
        span.glyphicon.glyphicon-lock
        | &nbsp;
      = time_ago_in_words @photo.updated_at
      | &nbsp;ago
    br
    = render 'comments/form'

    h4 Comments
    - @comments.each do |comment|
      .well.well-sm
        p
          - if comment.user == current_user
            = link_to [comment.photo.user, comment.photo, comment], data: {:confirm => 'Are you sure?'}, :method => :delete do
              span.glyphicon.glyphicon-remove.pull-right
          = comment.content
        p
          | by&nbsp;
          = link_to comment.user.name, comment.user
          span.pull-right
            = time_ago_in_words comment.updated_at
            | &nbsp;ago

  .col-sm-6
    - if current_user
      - if @photo.has_liked?(current_user)
        = link_to dislike_path(@photo.user, @photo), :method => :delete, class: "btn btn-danger" do
          span.glyphicon.glyphicon-thumbs-down
          | &nbsp; Unlike
      - else
        = link_to like_path(@photo.user, @photo), :method => :post, class: "btn btn-success"  do
          span.glyphicon.glyphicon-thumbs-up
          | &nbsp; Like

    - if @photo.like_users.any?
      h4.liked_users Liked by:
      - liked_users = @photo.like_users.collect do |user|
        - link_to "#{user.first_name} #{user.last_name}", user
      = liked_users.join(', ').html_safe

    - if @photo.tagged_users.any?
      h4.tagged_users Tagged:
      - @photo.tagged_users.each do |user|
        .btn-group
          = link_to "#{user.name}", user, class: "btn btn-default"
          = link_to untag_path(@photo.user, @photo, user), :method => :delete, class: "btn btn-default"  do
            span.glyphicon.glyphicon-remove
        span &nbsp;

    - if @photo.taggable_users.any?
      hr
      = simple_form_for [@user, @photo, @photo.taggings.new] do |f|
        .form-group
          = f.association :user, label: false, collection: @photo.taggable_users.map {|u| [u.name, u.id]}, required: true, autofocus: true, input_html: { class: "form-control selectize" }
        .form-actions
          = f.button :submit, "Tag", class: "btn btn-primary"