config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :photos

  resources :users, except: [:new, :destroy] do
    resources :photos do
      resources :comments, except: [:show, :update]
    end
  end

  root 'home#index'

  get '/search', to: 'users#search'

  get '/users/:id/friends', to: 'users#friends', as: :friends

  get '/users/:id/requests', to: 'users#requests', as: :requests

  post '/users/:id/befriend', to: 'users#befriend', as: :befriend

  post '/users/:id/accept', to: 'users#accept', as: :accept

  post '/users/:id/deny', to: 'users#deny', as: :deny

  post '/users/:user_id/photos/:id/like', to: 'photos#like', as: :like

  delete '/users/:user_id/photos/:id/dislike', to: 'photos#dislike', as: :dislike

  post '/users/:user_id/photos/:id/tag', to: 'photos#tag', as: :user_photo_taggings

  delete '/users/:user_id/photos/:id/untag/:tagged_user_id', to: 'photos#untag', as: :untag

end

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default
  .container
    ul.nav.navbar-nav.navbar-left
      li= link_to 'Home', root_path
      - if current_user
        li= link_to 'My profile', current_user
        - if current_user.friend_requests.any?
          li= link_to requests_path(current_user) do
            | Friend requests &nbsp;
            span.badge = current_user.friend_requests.size
        li= link_to 'Friends', friends_path(current_user)
        li= link_to 'New photo', new_user_photo_path(current_user)

    ul.nav.navbar-nav.navbar-right
      form class="navbar-form navbar-left" role="search" method="get" action=search_path
        .form-group
          .input-group
            input type="text" name="query" class="form-control" placeholder="Search"
            span class="input-group-btn"
              button type="submit" class="btn btn-default"
                span.glyphicon.glyphicon-search.search-button
      - if current_user
        li= link_to current_user.first_name, edit_user_path(current_user)
        li= link_to 'Log out', destroy_user_session_path, method: :delete
      - else
        li= link_to 'Log in', new_user_session_path
        li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
html
  head
    title Fluxx
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render 'layouts/navigation'
    .container
      = flash[:error]
      = flash[:notice]
      = flash[:warning]
      = yield